### ISSUE TITLE
Can't download playlist

### ISSUE THREAD

**Issue by Ashu** [Kevin-De-Koninck/Get-It#3] opened 2017-10-07 18:06 UTC

**Comment by Kevin-De-Koninck** [comment] 2017-10-07 18:32
Hi,

Can you provide more details?
- Which URL do you fill in?
- What happens?
- Can you download another playlist or another video?

I'll look at it tomorrow

**Comment by Ashu** [comment] 2017-10-07 18:42
I get this error:
![screen shot 2017-10-08 at 12 12 02 am](https://user-images.githubusercontent.com/253385/31310860-5dce2f2a-abbd-11e7-8ded-30b947bc824f.png)

Playlist link: https://www.youtube.com/watch?v=JGwWNGJdvx8&list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG

**Comment by Kevin-De-Koninck** [comment] 2017-10-07 18:48
Can you also provide an overview of your settings (audio and video tab)?

**Comment by Ashu** [comment] 2017-10-07 19:00
![screen shot 2017-10-08 at 12 27 19 am](https://user-images.githubusercontent.com/253385/31310949-97e8a21a-abbf-11e7-9f15-a5e13d9df916.png)
![screen shot 2017-10-08 at 12 27 27 am](https://user-images.githubusercontent.com/253385/31310950-97f06c48-abbf-11e7-9dd8-db0759abaa4f.png)

**Comment by Kevin-De-Koninck** [comment] 2017-10-07 19:09
So the problem is that the video format is not available (see error description). This means that your wanted full HD resolution in the mp4 container could not be downloaded (probably one video that does not have the required quality). A possible solution is then to lower the wanted resolution to, e.g. 720p (which works, just tested it).

Will close this issue now, as it is resolved. Reopen if you have any questions.

**Closed as completed by Kevin-De-Koninck** 2017-10-07 19:09 UTC
